version: '2.9'
services:
    app:
        container_name: python_container
        build: ./init/
        environment:
            - PYTHONUNBUFFERED=1
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
    db:
        image: postgres:latest
        container_name: postgres_container
        hostname: db
        ports: 
            - 5432:5432
        env_file:
            - ./init/db_config.env
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "lapis_db", "-U", "postgres"]
            interval: 5s
            retries: 5
        restart: always